### ISSUE TITLE
fix - bypass KAV 

### ISSUE THREAD

**Issue by 827Dream** [0xsp-SRD/mortar#3]
there is little problem in your Readme , it is "sekurlsa::logonpasswords "" not "sekurlasa::logonpasswords"
`deliver.exe -d -c sekurlasa::logonpasswords -f mimikatz.enc --->deliver.exe -d -c sekurlsa::logonpasswords -f mimikatz.enc`

and then.. I want to confirm one thing .  i test this command `deliver.exe -d  -c version -f bin.enc `  and it execute successful  . But trigger the karspersky  (may be memory scan) after a few seconds , You also tested this mentioned in your article and didn't this problem occur at the time?
<img width="726" alt="fcba68b9e1ebf65899a5b9bc80518d4" src="https://user-images.githubusercontent.com/52020508/147062715-08dd1abc-aeda-4ef4-8a83-0c94891fd3ad.png">

**Comment by lawrenceamer** [comment]
tnx yeah I fixed the typos problem, regarding the KAV detection for loader.exe, I think that's could happen in some cases as KAV is good in mem scan but I am sure for DLL release will not be able to detect! have you tried?

**Comment by 827Dream** [comment]
> tnx yeah I fixed the typos problem, regarding the KAV detection for loader.exe, I think that's could happen in some cases as KAV is good in mem scan but I am sure for DLL release will not be able to detect! have you tried?


hi I try this just now but the result might let you down , it can still be scanned after a few seconds . May be we need find an other way to evade mem scan .at the end you did a great job ：）and 
thanks reply!
<img width="760" alt="ccad98373715d6b44688865cd97da46" src="https://user-images.githubusercontent.com/52020508/147078908-77e46a70-3179-4b31-80d9-3023a72c3987.png">

**Comment by lawrenceamer** [comment]
I think it is fine, everything can be bypassed, could you please share me the following information
* KAV version +database version 
* x64 or x68
* can you try to change the following values at this line https://github.com/0xsp-SRD/mortar/blob/main/Lib/runner.pas#L180 in the source code into 
```
ReadProcessMemory(PI.hProcess, Pointer(CONT.rdx + $10), @Addr, 8, Ret);

```
and compile it EXE or DLL and forward the results again

**Comment by 827Dream** [comment]
> 

hi, I modified the code as you said and get the same result . i can not find database version and just a 
Update time . i get the kav Advanced Suite trial version from here [https://www.kaspersky.co.in/downloads](url)
<img width="880" alt="2cfb1e4c47aefdba0d51a021dbc5f6f" src="https://user-images.githubusercontent.com/52020508/147177869-3a8f8ab5-5109-4273-8cec-7d7add9d6130.png">
<img width="379" alt="1c739349c1b6ba8eed7b795d0ae3e07" src="https://user-images.githubusercontent.com/52020508/147177882-f4bf69bb-db84-43ad-8d19-55bfeb08e350.png">

**Comment by lawrenceamer** [comment]
KAV has been defeated successfully, do the following : 
- put the encrypted bin.enc in your current user path for example c:\users\tester 
- use any dll injector (reflective loader/ dll injection / side loading ) 
- choose cmd.exe process to inject and successfully get bypass 
here is the video of bypass 
https://video.0xsp.com/conversations/eb396ad5-f9f1-5afa-b171-30b812c8a9de

**Comment by Jack-Reve** [comment]
Hello lawrenceamer, hope you are well.
I have a question, how can I call the export function "dec" and execute it when I injected the dll into "cmd.exe" process, or what is the technique, the reflective injector you are used to do that.
because when I injected the dll into the cmd.exe process it is just injected and didn't execute "dec" function to run the ".enc" payload and get my shell.

**Comment by Jack-Reve** [comment]
Hello lawrenceamer, hope you are well.
I have a question, how can I call the export function "dec" and execute it when I injected the dll into "cmd.exe" process, or what is the technique, the reflective injector you are used to do that.
because when I injected the dll into the cmd.exe process it is just injected and didn't execute "dec" function to run the ".enc" payload and get my shell.

**Comment by goofsec** [comment]
Hi @Jack-Reve, try to call your decrypt function in agressor.lpr (e.g. in line 214). based on my understanding you need to call it manually, since the dll has no DllMain entry point and only two export functions. After that, open a cmd, _cd_ to the folder where your bin.enc is saved and inject the agressor.lpr into this cmd.

@lawrenceamer this way I was able to bypass Sophos, maybe you want to add it to your list in README.md ;)

**Comment by lawrenceamer** [comment]
@goofsec thanks. You may also try the following technique to bypass KAV and others @Jack-Reve 

* put the bin.enc on the user folder e.g c:/users/tester/ 
* Open any dll injector tool
* select x64 process want to inject with the aggressor 
* bypass the memory scan

**Comment by icass** [comment]
Wtf
